const storyProgression = {
    welcome: ["start"],
        start: ["the_dare"],
            the_dare: ["enter_together", "go_home"],
            go_home: ["enter_together"],
                enter_together: ["enter_library", "hum_or_shadow"],
                    enter_library: ["read_contents", "examine_binding"],
                        examine_binding: ["kidnapped"],
                            kidnapped: ["rescue"],
                                rescue: ["rescue_complete"],
                                    rescue_complete: ["play_again"],
                                        play_again: ["start"],
                        read_contents: ["play_again"],
                            play_again: ["start"],
                    hum_or_shadow: ["inspect_basement", "inspect_shadowy_room"],
                        inspect_basement: ["creep_in_dark", "use_torch"],
                            creep_in_dark: ["kidnapped"],
                                kidnapped: ["rescue"],
                                    rescue: ["rescue_complete"],
                                        rescue_complete: ["play_again"],
                                            play_again: ["start"],
                            use_torch: ["listen_in", "flee_and_fail"],
                            listen_in: ["record_ritual", "cause_chaos"],
                                record_ritual: ["play_again"],
                                    play_again: ["start"],
                                cause_chaos: ["chaos_continued"],
                                chaos_continued: ["chaos_complete"],
                                chaos_complete: ["play_again"],
                                    play_again: ["start"],
                            flee_and_fail: ["kidnapped"],                            
                        inspect_shadowy_room: ["inspect_shadowy_room_part_two"],
                            inspect_shadowy_room_part_two: ["run_from_shadowy", "fight_shadowy"],
                                run_from_shadowy: ["play_again"],
                                    play_again: ["start"],
                                fight_shadowy: ["play_again"],
                                    play_again: ["start"],
                };